---
- name: copy file to EC2
  become: yes
  template:
    src: /root/project/roles/deploy/files/artifact.tar.gz
    dest: /home/ubuntu/

- name: Unarchive backend files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: start server
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start main.js -f

