---
- name: Unarchive backend files
  unarchive:
    src: /home/circleci/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: /home/ubuntu/

- name: start server
  become: true
  shell: |
    cd /home/ubuntu/dist
    pm2 start npm -- run start

