---


- name: Unarchive backend files
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: start server
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start main.js -f

